version: '3'
services:
  master_postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  master_redis:
    image: redis:latest
    ports:
      - "6379:6379"